# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmsapp', '0003_auto_20160403_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bare_metal_servers',
            name='name',
        ),
        migrations.AlterField(
            model_name='bare_metal_servers',
            name='cpus',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cloud_types',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='managers',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='network_types',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='networks',
            name='range',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vms',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
