# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itmsapp', '0004_auto_20160403_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmsapp.managers'),
        ),
    ]
