# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itmsapp', '0005_auto_20160403_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bare_metal_servers',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmsapp.networks'),
        ),
        migrations.AlterField(
            model_name='clouds',
            name='assigned_to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmsapp.projects'),
        ),
        migrations.AlterField(
            model_name='clouds',
            name='networks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmsapp.networks'),
        ),
        migrations.AlterField(
            model_name='clouds',
            name='nodes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmsapp.bare_metal_servers'),
        ),
        migrations.AlterField(
            model_name='networks',
            name='network_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmsapp.network_types'),
        ),
        migrations.AlterField(
            model_name='vms',
            name='cloud_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmsapp.clouds'),
        ),
        migrations.AlterField(
            model_name='vms',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmsapp.networks'),
        ),
    ]
