# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmsapp', '0006_auto_20160403_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouds',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
